
volumes:                                       # Define shared volumes for data persistence
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lannur-s/data/db           # Specify path for MariaDB data

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lannur-s/data/wp          # Specify path for WordPress data

networks:
  inception-nw:
    driver: bridge  # Use bridge driver for network

services:

#------------------------------------------ MARIADB ------------------------------------------#
  mariadb:                               # Define the MariaDB service
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql                   # Persist database data in a volume
    networks:
      - inception-nw                        # Connect to the custom network
    init: true                              # Ensure containers are initialized properly
    restart: on-failure                     # Restart the container on failure

# Explanation of Dependency:
# MariaDB runs independently and is the first service in the dependency chain. 
# It must be up and running before WordPress
# WordPress needs a functioning database connection to store its data

#----------------------------------------- WORDPRESS -----------------------------------------#
  wordpress:                             # Define the WordPress service
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/wordpress        # Persist WordPress files in a volume
    networks:
      - inception-nw
    init: true
    restart: on-failure
    depends_on:
      - mariadb                             # Ensure MariaDB starts before WordPress

# Explanation of Dependency:
# WordPress depends on MariaDB. 
# WordPress is started only after MariaDB is up.
# Thus WordPress can initialize with a live database connection, preventing connection errors

#----------------------------------------- NGINX ------------------------------------------#
  nginx:                                 # Define the NGINX service
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - '443:443'                           # Map port 443 for HTTPS access
    volumes:
     - wp:/var/www/wordpress        # Share volume with WordPress for web files
    networks:
      - inception-nw
    init: true
    restart: on-failure
    depends_on:
     - wordpress                           # Ensure WordPress starts before NGINX

# Explanation of Dependency:
# NGINX depends on WordPress. 
# Ensures WordPress is running before starting NGINX.
# Thus NGINX serves WordPress content over HTTPS without content or configuration errors
