version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "443:443"
    volumes:
      - ./srcs/nginx:/etc/nginx/conf.d
      - ./srcs/certs:/etc/nginx/certs
    networks:
      - my_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
    ports:
      - "8080:80"
    volumes:
      - ./srcs/wordpress:/var/www/html
    networks:
      - my_network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
