
volumes:                                       # Define shared volumes for data persistence
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lannur-s/data/mariadb         # Specify path for MariaDB data

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lannur-s/data/wordpress       # Specify path for WordPress data

networks:
  inception-nw:
    name: lannur-s-inception  # Custom network name
    driver: bridge  # Use bridge driver for network

services:

#------------------------------------------ MARIADB ------------------------------------------#
  mariadb:                               # Define the MariaDB service
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql              # Persist database data in a volume
    secrets:
      - credentials                         # Securely pass credentials
      - db_password                         # Pass the database password as a secret
      - db_root_password                    # Pass the root password as a secret
    networks:
      - inception-nw                        # Connect to the custom network
    init: true                              # Ensure containers are initialized properly
    restart: on-failure                     # Restart the container on failure

# Explanation of Dependency:
# MariaDB runs independently and is the first service in the dependency chain. 
# It must be up and running before WordPress
# WordPress needs a functioning database connection to store its data

#----------------------------------------- WORDPRESS -----------------------------------------#
  wordpress:                             # Define the WordPress service
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress        # Persist WordPress files in a volume
    secrets:
      - credentials
      - db_password
    networks:
      - inception-nw
    init: true
    restart: on-failure
    depends_on:
      - mariadb                             # Ensure MariaDB starts before WordPress

# Explanation of Dependency:
# WordPress depends on MariaDB. 
# WordPress is started only after MariaDB is up.
# Thus WordPress can initialize with a live database connection, preventing connection errors

#----------------------------------------- NGINX ------------------------------------------#
  nginx:                                 # Define the NGINX service
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - '443:443'                           # Map port 443 for HTTPS access
    volumes:
      - wordpress:/var/www/wordpress        # Share volume with WordPress for web files
    networks:
      - inception-nw
    init: true
    restart: on-failure
    depends_on:
      - wordpress                           # Ensure WordPress starts before NGINX

# Explanation of Dependency:
# NGINX depends on WordPress. 
# Ensures WordPress is running before starting NGINX.
# Thus NGINX serves WordPress content over HTTPS without content or configuration errors


secrets:                                      # Define secrets for secure sensitive data storage
  credentials:
    file: ~/inception/secrets/credentials.txt # Path to credentials file
  db_password:
    file: ~/inception/secrets/db_password.txt
  db_root_password:
    file: ~/inception/secrets/db_root_password.txt
