services:
  # service name and image name has to be the same to avoid below warning
  # pull access denied for <name>, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
  mariadb:
    image: mariadb
    build:
     context: requirements/mariadb
     dockerfile: "Dockerfile"
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
    env_file:
        .env
    networks:
      - my_network
    restart: unless-stopped


volumes:
  db_data:

networks:
  my_network:
    driver: bridge
